apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data: 
  userEnvKey: http://userservice-deployment-service
  orderEnvKey: http://orderservice-deployment-service
  